### ISSUE TITLE
Submersible window gets stuck open when dealing with Airship redeployment

### ISSUE THREAD

**Issue by zbee** [PunishXIV/AutoRetainer#56]
I set in multimode last night, and I come back to find it didn't do anything after my airship returned as it is stuck on this screen:
![image](https://github.com/PunishXIV/AutoRetainer/assets/1582821/de0f44e0-5cde-4fa7-8ccc-65b2100a9f67)

I can't even escape out of this menu, because it just clicks it again.

These are my deployable settings:
![image](https://github.com/PunishXIV/AutoRetainer/assets/1582821/5f45fe3c-c00b-407e-85b3-361ea6943e23)

<details>
<summary>Here are the logs from the point that it tried to send out the airship:</summary>

```
08:55:13.296 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskEnterWorkshop
08:55:13.319 | DBG [AutoRetainer] Starting to execute task: WaitForYesAlreadyDisabledTask
08:55:13.335 | DBG [AutoRetainer] Task WaitForYesAlreadyDisabledTask completed successfully
08:55:13.352 | DBG [AutoRetainer] Starting to execute task: <Enqueue>b__0
08:55:13.369 | DBG [AutoRetainer] Task <Enqueue>b__0 completed successfully
08:55:13.385 | DBG [AutoRetainer] Starting to execute task: WaitUntilNotBusy
08:55:19.458 | DBG [AutoRetainer] Task WaitUntilNotBusy completed successfully
08:55:19.475 | DBG [AutoRetainer] Starting to execute task: Master HET
08:55:19.492 | DBG [AutoRetainer] Task Master HET completed successfully
08:55:19.508 | DBG [AutoRetainer] Starting to execute immediate task: <EnqueueTask>b__2_9
08:55:19.525 | DBG [AutoRetainer] Setting entrance target (5)
08:55:19.525 | DBG [AutoRetainer] Task <EnqueueTask>b__2_9 completed successfully
08:55:19.541 | DBG [AutoRetainer] Starting to execute immediate task: Interact
08:55:19.558 | DBG [AutoRetainer] Interacting with entrance
08:55:19.559 | DBG [AutoRetainer] Task Interact completed successfully
08:55:19.575 | DBG [AutoRetainer] Starting to execute immediate task: SelectYesno
08:55:20.009 | DBG [AutoRetainer] Select yes
08:55:20.009 | DBG [AutoRetainer] Task SelectYesno completed successfully
08:55:20.025 | DBG [AutoRetainer] Starting to execute immediate task: WaitUntilLeavingZone
08:55:22.399 | DBG [AutoRetainer] Task WaitUntilLeavingZone completed successfully
08:55:22.406 | DBG [AutoRetainer] Starting to execute immediate task: FrameThrottler.Throttle(ECommonsGenericDelay, 60)
08:55:22.416 | DBG [AutoRetainer] Task FrameThrottler.Throttle(ECommonsGenericDelay, 60) completed successfully
08:55:22.422 | DBG [AutoRetainer] Starting to execute immediate task: FrameThrottler.Check(ECommonsGenericDelay)
08:55:22.866 | DBG [AutoRetainer] Task FrameThrottler.Check(ECommonsGenericDelay) completed successfully
08:55:22.899 | DBG [AutoRetainer] Starting to execute task: WaitUntilNotOccupied1
08:55:23.865 | DBG [AutoRetainer] Task WaitUntilNotOccupied1 completed successfully
08:55:23.882 | DBG [AutoRetainer] Starting to execute task: <Enqueue>b__0
08:55:23.898 | DBG [AutoRetainer] Task <Enqueue>b__0 completed successfully
08:55:23.915 | DBG [AutoRetainer] Starting to execute immediate task: WaitUntilNotOccupied2
08:55:23.932 | DBG [AutoRetainer] Task WaitUntilNotOccupied2 completed successfully
08:55:23.948 | DBG [AutoRetainer] Starting to execute immediate task: LockonAdditionalChambers
08:55:23.967 | DBG [AutoRetainer] Setting entrance target (E0000000(Entrance to Additional Chambers - EventObj) at 30B98D74200)
08:55:23.984 | DBG [AutoRetainer] Task LockonAdditionalChambers completed successfully
08:55:24.000 | DBG [AutoRetainer] Starting to execute immediate task: Approach
08:55:24.017 | DBG [AutoRetainer] Enabling automove
08:55:24.017 | DBG [AutoRetainer] Random regenerated: 0.5093802
08:55:24.017 | DBG [AutoRetainer] Task Approach completed successfully
08:55:24.033 | DBG [AutoRetainer] Starting to execute immediate task: AutorunOffAdd
08:55:24.904 | DBG [AutoRetainer] Disabling automove
08:55:24.904 | DBG [AutoRetainer] Task AutorunOffAdd completed successfully
08:55:24.917 | DBG [AutoRetainer] Starting to execute immediate task: <EnqueueImmediate>b__0
08:55:24.934 | DBG [AutoRetainer] Task <EnqueueImmediate>b__0 completed successfully
08:55:24.950 | DBG [AutoRetainer] Starting to execute immediate task: InteractAdd
08:55:24.967 | DBG [AutoRetainer] Interacting with entrance
08:55:24.967 | DBG [AutoRetainer] Task InteractAdd completed successfully
08:55:24.984 | DBG [AutoRetainer] Starting to execute immediate task: SelectEnterWorkshop
08:55:25.618 | DBG [AutoRetainer] TrySelectSpecificEntry: selecting Move to the company workshop/0
08:55:25.618 | DBG [AutoRetainer] Confirmed going to workhop
08:55:25.618 | DBG [AutoRetainer] Task SelectEnterWorkshop completed successfully
08:55:25.634 | DBG [AutoRetainer] Starting to execute immediate task: Wait Until entered workshop
08:55:27.143 | DBG [AutoRetainer] Task Wait Until entered workshop completed successfully
08:55:27.150 | DBG [AutoRetainer] Starting to execute immediate task: FrameThrottler.Throttle(ECommonsGenericDelay, 60)
08:55:27.156 | DBG [AutoRetainer] Task FrameThrottler.Throttle(ECommonsGenericDelay, 60) completed successfully
08:55:27.163 | DBG [AutoRetainer] Starting to execute immediate task: FrameThrottler.Check(ECommonsGenericDelay)
08:55:27.609 | DBG [AutoRetainer] Task FrameThrottler.Check(ECommonsGenericDelay) completed successfully
08:55:27.609 | DBG [AutoRetainer] YesAlready unlocked
08:55:27.609 | DBG [AutoRetainer] FPS restrictions restored
08:55:27.609 | DBG [AutoRetainer] Restoring FFXIV process priority.
08:55:27.609 | DBG [AutoRetainer] TextAdvance unlocked
08:57:01.913 | DBG [AutoRetainer] Enqueueing interaction with panel
08:57:01.913 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskInteractWithNearestPanel interact=True
08:57:01.913 | DBG [AutoRetainer] Added interaction because of interacting (state: 251451421)
08:57:01.913 | DBG [AutoRetainer] YesAlready locked
08:57:01.913 | DBG [AutoRetainer] FPS restrictions removed
08:57:01.913 | DBG [AutoRetainer] Setting FFXIV process priority to high.
08:57:01.913 | DBG [AutoRetainer] TextAdvance locked
08:57:01.930 | DBG [AutoRetainer] Starting to execute task: ApproachPanelIfNeeded
08:57:01.946 | DBG [AutoRetainer] Task ApproachPanelIfNeeded completed successfully
08:57:01.963 | DBG [AutoRetainer] Starting to execute immediate task: Lockon
08:57:01.980 | DBG [AutoRetainer] [Voyage] Targeting workshop CP
08:57:02.080 | DBG [AutoRetainer] [Voyage] Locking on workshop CP
08:57:02.080 | DBG [AutoRetainer] Task Lockon completed successfully
08:57:02.097 | DBG [AutoRetainer] Starting to execute immediate task: Approach
08:57:02.180 | DBG [AutoRetainer] Random regenerated: 0.14039846
08:57:02.180 | DBG [AutoRetainer] Task Approach completed successfully
08:57:02.197 | DBG [AutoRetainer] Starting to execute immediate task: AutomoveOffPanel
08:57:02.814 | DBG [AutoRetainer] Task AutomoveOffPanel completed successfully
08:57:02.830 | DBG [AutoRetainer] Starting to execute task: InteractWithVoyagePanel
08:57:02.914 | DBG [AutoRetainer] [Voyage] Interacting with workshop CP
08:57:02.914 | DBG [AutoRetainer] Task InteractWithVoyagePanel completed successfully
08:57:02.914 | DBG [AutoRetainer] Entered voyage panel
08:57:02.914 | DBG [AutoRetainer] <!> Enabled voyage scheduler
08:57:02.930 | DBG [AutoRetainer] Starting to execute task: <Enqueue>b__0
08:57:02.947 | DBG [AutoRetainer] Task <Enqueue>b__0 completed successfully
08:57:02.947 | DBG [AutoRetainer] FPS restrictions restored
08:57:02.947 | DBG [AutoRetainer] Restoring FFXIV process priority.
08:57:03.180 | DBG [AutoRetainer] Starting to execute task: SelectAirshipManagement
08:57:03.181 | DBG [AutoRetainer] FPS restrictions removed
08:57:03.181 | DBG [AutoRetainer] Setting FFXIV process priority to high.
08:57:03.198 | DBG [AutoRetainer] TrySelectSpecificEntry: selecting Airship Management/0
08:57:03.198 | DBG [AutoRetainer] Task SelectAirshipManagement completed successfully
08:57:03.198 | DBG [AutoRetainer] FPS restrictions restored
08:57:03.199 | DBG [AutoRetainer] Restoring FFXIV process priority.
08:57:03.717 | DBG [AutoRetainer] [Voyage] Updated airship data from AirshipStatus
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskFinalizeVessel name=Company Airship-1, type=Airship, quit=False
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskSelectVesselByName (Company Airship-1)
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
08:57:03.799 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskDeployAndSkipCutscene validate=True
08:57:03.814 | DBG [AutoRetainer] Starting to execute task: TaskSelectVesselByName: Company Airship-1
08:57:03.815 | DBG [AutoRetainer] FPS restrictions removed
08:57:03.815 | DBG [AutoRetainer] Setting FFXIV process priority to high.
08:57:03.831 | DBG [AutoRetainer] Selecting vessel Company Airship-1/Airship/Company Airship-1. (Rank: 35)  [Voyage complete]/0
08:57:03.831 | DBG [AutoRetainer] Task TaskSelectVesselByName: Company Airship-1 completed successfully
08:57:03.848 | DBG [AutoRetainer] Starting to execute task: FinalizeVessel
08:57:04.999 | DBG [AutoRetainer] Task FinalizeVessel completed successfully
08:57:05.016 | DBG [AutoRetainer] Starting to execute task: WaitForSelectStringAddon
08:57:09.626 | DBG [AutoRetainer] Task WaitForSelectStringAddon completed successfully
08:57:09.643 | DBG [AutoRetainer] Starting to execute task: IntelligentRepairTask
08:57:09.659 | DBG [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 22944, index: 1, id: 10164, cond: 23154, index: 2, id: 10168, cond: 22860, index: 3, id: 10175, cond: 22944
08:57:09.659 | DBG [AutoRetainer] Task IntelligentRepairTask completed successfully
08:57:09.676 | DBG [AutoRetainer] Starting to execute task: IntelligentRepairTask
08:57:09.693 | DBG [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 22944, index: 1, id: 10164, cond: 23154, index: 2, id: 10168, cond: 22860, index: 3, id: 10175, cond: 22944
08:57:09.693 | DBG [AutoRetainer] Task IntelligentRepairTask completed successfully
08:57:09.710 | DBG [AutoRetainer] Starting to execute task: SelectDeploy
08:57:29.720 | WRN [AutoRetainer] Clearing 7 remaining tasks because of timeout
08:57:29.721 | WRN [AutoRetainer] Task SelectDeploy took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in C:\VS\AutoRetainer\ECommons\ECommons\Automation\TaskManager.cs:line 284
08:57:29.721 | DBG [AutoRetainer] FPS restrictions restored
08:57:29.721 | DBG [AutoRetainer] Restoring FFXIV process priority.
11:08:21.492 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskSelectVesselByName (Company Airship-1)
11:08:21.492 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:08:21.492 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
11:08:21.492 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:08:21.492 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskDeployAndSkipCutscene validate=True
11:08:21.508 | DBG [AutoRetainer] Starting to execute task: TaskSelectVesselByName: Company Airship-1
11:08:21.509 | DBG [AutoRetainer] FPS restrictions removed
11:08:21.509 | DBG [AutoRetainer] Setting FFXIV process priority to high.
11:08:21.525 | DBG [AutoRetainer] Selecting vessel Company Airship-1/Airship/Company Airship-1. (Rank: 36) /0
11:08:21.525 | DBG [AutoRetainer] Task TaskSelectVesselByName: Company Airship-1 completed successfully
11:08:21.541 | DBG [AutoRetainer] Starting to execute task: IntelligentRepairTask
11:08:21.558 | DBG [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 22944, index: 1, id: 10164, cond: 23154, index: 2, id: 10168, cond: 22860, index: 3, id: 10175, cond: 22944
11:08:21.558 | DBG [AutoRetainer] Task IntelligentRepairTask completed successfully
11:08:21.575 | DBG [AutoRetainer] Starting to execute task: SelectDeploy
11:08:41.600 | WRN [AutoRetainer] Clearing 7 remaining tasks because of timeout
11:08:41.600 | WRN [AutoRetainer] Task SelectDeploy took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in C:\VS\AutoRetainer\ECommons\ECommons\Automation\TaskManager.cs:line 284
11:08:41.600 | DBG [AutoRetainer] FPS restrictions restored
11:08:41.600 | DBG [AutoRetainer] Restoring FFXIV process priority.
{ } [ Send ]

```
</details>

<details>
<summary>If I clear the log and try to exit the menu, these are the logs that re-appear when it forces me back into the menu, unable to escape:</summary>

```
11:22:55.722 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskSelectVesselByName (Company Airship-1)
11:22:55.722 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:22:55.722 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
11:22:55.722 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:22:55.722 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskDeployAndSkipCutscene validate=True
11:22:55.738 | DBG [AutoRetainer] Starting to execute task: TaskSelectVesselByName: Company Airship-1
11:22:55.739 | DBG [AutoRetainer] FPS restrictions removed
11:22:55.739 | DBG [AutoRetainer] Setting FFXIV process priority to high.
11:22:55.755 | DBG [AutoRetainer] Selecting vessel Company Airship-1/Airship/Company Airship-1. (Rank: 36) /0
11:22:55.755 | DBG [AutoRetainer] Task TaskSelectVesselByName: Company Airship-1 completed successfully
11:22:55.771 | DBG [AutoRetainer] Starting to execute task: IntelligentRepairTask
11:22:55.788 | DBG [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 22944, index: 1, id: 10164, cond: 23154, index: 2, id: 10168, cond: 22860, index: 3, id: 10175, cond: 22944
11:22:55.788 | DBG [AutoRetainer] Task IntelligentRepairTask completed successfully
11:22:55.805 | DBG [AutoRetainer] Starting to execute task: SelectDeploy
11:23:15.812 | WRN [AutoRetainer] Clearing 7 remaining tasks because of timeout
11:23:15.812 | WRN [AutoRetainer] Task SelectDeploy took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in C:\VS\AutoRetainer\ECommons\ECommons\Automation\TaskManager.cs:line 284
11:23:15.813 | DBG [AutoRetainer] FPS restrictions restored
11:23:15.813 | DBG [AutoRetainer] Restoring FFXIV process priority.
{ } [ Send ]
```
</details>

<details>
<summary>If I uncheck the airship in the deployable menu, then try to press escape to close the menu, this is what I get:</summary>

```
11:24:27.590 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskQuitMenu
11:24:27.606 DBG | [AutoRetainer] Starting to execute task: SelectQuitVesselSelectorMenu
11:24:27.607 DBG | [AutoRetainer] FPS restrictions removed
11:24:27.607 DBG | [AutoRetainer] Setting FFXIV process priority to high.
11:24:27.623 DBG | [AutoRetainer] TrySelectSpecificEntry: selecting Nothing./1
11:24:27.623 DBG | [AutoRetainer] Task SelectQuitVesselSelectorMenu completed successfully
11:24:27.623 DBG | [AutoRetainer] FPS restrictions restored
11:24:27.624 DBG | [AutoRetainer] Restoring FFXIV process priority.
11:24:27.973 DBG | [AutoRetainer] Starting to execute task: SelectExitMainPanel
11:24:27.973 DBG | [AutoRetainer] FPS restrictions removed
11:24:27.973 DBG | [AutoRetainer] Setting FFXIV process priority to high.
11:24:27.990 DBG | [AutoRetainer] TrySelectSpecificEntry: selecting Cancel/2
11:24:27.990 DBG | [AutoRetainer] Task SelectExitMainPanel completed successfully
11:24:27.990 DBG | [AutoRetainer] FPS restrictions restored
11:24:27.990 DBG | [AutoRetainer] Restoring FFXIV process priority.
11:24:28.223 DBG | [AutoRetainer] <!> Exited voyage panel, disabled voyage scheduler
11:24:28.240 DBG | [AutoRetainer] YesAlready unlocked
11:24:28.240 DBG | [AutoRetainer] TextAdvance unlocked
11:24:31.391 DBG | [AutoRetainer] Enqueueing interaction with bell
11:24:31.391 DBG | [AutoRetainer] Added interaction because of interacting (state: 251451421, 260300906)
11:24:31.391 DBG | [AutoRetainer] YesAlready locked
11:24:31.391 DBG | [AutoRetainer] FPS restrictions removed
11:24:31.391 DBG | [AutoRetainer] Setting FFXIV process priority to high.
11:24:31.391 DBG | [AutoRetainer] TextAdvance locked
11:24:31.407 DBG | [AutoRetainer] Starting to execute task: WaitForYesAlreadyDisabledTask
11:24:31.424 DBG | [AutoRetainer] Task WaitForYesAlreadyDisabledTask completed successfully
11:24:31.440 DBG | [AutoRetainer] Starting to execute task: ApproachWorkshopBell
```
</details>

Before the next log dump I also tried to manually repair the not-broken airship parts.

<details>
<summary>If I clear the log again, with the menu closed and the character ready to do stuff again, and turn back on the airship to try to make autoretainer send it out, I get this:</summary>

```
11:29:10.520 | DBG [AutoRetainer] Entered voyage panel
11:29:10.520 | DBG [AutoRetainer] <!> Enabled voyage scheduler
11:29:10.527 | INF [AutoRetainer] Starting ThreadLoadImageHandler
11:29:10.527 | INF [AutoRetainer] Loading image C:\Users\Pwnjo\AppData\Roaming\XIVLauncher\installedPlugins\AutoRetainer\4.2.2.5\res\submarine.png
11:29:10.537 | DBG [AutoRetainer] YesAlready locked
11:29:10.537 | DBG [AutoRetainer] TextAdvance locked
11:29:10.953 | DBG [AutoRetainer] Starting to execute task: SelectAirshipManagement
11:29:10.953 | DBG [AutoRetainer] FPS restrictions removed
11:29:10.954 | DBG [AutoRetainer] Setting FFXIV process priority to high.
11:29:10.970 | DBG [AutoRetainer] TrySelectSpecificEntry: selecting Airship Management/0
11:29:10.970 | DBG [AutoRetainer] Task SelectAirshipManagement completed successfully
11:29:10.970 | DBG [AutoRetainer] FPS restrictions restored
11:29:10.970 | DBG [AutoRetainer] Restoring FFXIV process priority.
11:29:11.505 | DBG [AutoRetainer] [Voyage] Updated airship data from AirshipStatus
11:29:11.588 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskSelectVesselByName (Company Airship-1)
11:29:11.588 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:29:11.588 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
11:29:11.588 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:29:11.588 | DBG [AutoRetainer] [Voyage] Task enqueued: TaskDeployAndSkipCutscene validate=True
11:29:11.604 | DBG [AutoRetainer] Starting to execute task: TaskSelectVesselByName: Company Airship-1
11:29:11.604 | DBG [AutoRetainer] FPS restrictions removed
11:29:11.604 | DBG [AutoRetainer] Setting FFXIV process priority to high.
11:29:11.621 | DBG [AutoRetainer] Selecting vessel Company Airship-1/Airship/Company Airship-1. (Rank: 36) /0
11:29:11.621 | DBG [AutoRetainer] Task TaskSelectVesselByName: Company Airship-1 completed successfully
11:29:11.637 | DBG [AutoRetainer] Starting to execute task: IntelligentRepairTask
11:29:11.654 | DBG [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 22944, index: 1, id: 10164, cond: 23154, index: 2, id: 10168, cond: 22860, index: 3, id: 10175, cond: 22944
11:29:11.654 | DBG [AutoRetainer] Task IntelligentRepairTask completed successfully
11:29:11.670 | DBG [AutoRetainer] Starting to execute task: SelectDeploy
11:29:20.612 | INF [AutoRetainer] Stopping ThreadLoadImageHandler, ticks=100
11:29:31.698 | WRN [AutoRetainer] Clearing 7 remaining tasks because of timeout
11:29:31.698 | WRN [AutoRetainer] Task SelectDeploy took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in C:\VS\AutoRetainer\ECommons\ECommons\Automation\TaskManager.cs:line 284
11:29:31.699 | DBG [AutoRetainer] FPS restrictions restored
11:29:31.699 | DBG [AutoRetainer] Restoring FFXIV process priority.
{ } [ Send ]
```
</details>

<details>
<summary>If I enable extra logging and repeat the last step: (this looks to be the same-ish amount of logs as the last time)</summary>

```
11:34:11.059 DBG | [AutoRetainer] Entered voyage panel
11:34:11.059 DBG | [AutoRetainer] <!> Enabled voyage scheduler
11:34:11.076 DBG | [AutoRetainer] YesAlready locked
11:34:11.076 DBG | [AutoRetainer] TextAdvance locked
11:34:11.259 DBG | [AutoRetainer] Starting to execute task: SelectAirshipManagement
11:34:11.259 DBG | [AutoRetainer] FPS restrictions removed
11:34:11.259 DBG | [AutoRetainer] Setting FFXIV process priority to high.
11:34:11.276 DBG | [AutoRetainer] TrySelectSpecificEntry: selecting Airship Management/0
11:34:11.276 DBG | [AutoRetainer] Task SelectAirshipManagement completed successfully
11:34:11.276 DBG | [AutoRetainer] FPS restrictions restored
11:34:11.276 DBG | [AutoRetainer] Restoring FFXIV process priority.
11:34:11.794 DBG | [AutoRetainer] [Voyage] Updated airship data from AirshipStatus
11:34:11.877 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskSelectVesselByName (Company Airship-1)
11:34:11.877 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:34:11.877 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskIntelligentRepair, name=Company Airship-1, type=Airship
11:34:11.877 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskCalculateAndPickBestExpRoute (plan: {"GUID":"f88f7fee-6d2a-4b84-b48c-6c554c60f942","Name":"Plan Unlock","ExcludedRoutes":[],"UnlockSubs":true})
11:34:11.877 DBG | [AutoRetainer] [Voyage] Task enqueued: TaskDeployAndSkipCutscene validate=True
11:34:11.893 DBG | [AutoRetainer] Starting to execute task: TaskSelectVesselByName: Company Airship-1
11:34:11.894 DBG | [AutoRetainer] FPS restrictions removed
11:34:11.894 DBG | [AutoRetainer] Setting FFXIV process priority to high.
11:34:11.910 DBG | [AutoRetainer] Selecting vessel Company Airship-1/Airship/Company Airship-1. (Rank: 36) /0
11:34:11.910 DBG | [AutoRetainer] Task TaskSelectVesselByName: Company Airship-1 completed successfully
11:34:11.926 DBG | [AutoRetainer] Starting to execute task: IntelligentRepairTask
11:34:11.943 DBG | [AutoRetainer] Repair check log: index: 0, id: 10157, cond: 30000, index: 1, id: 10164, cond: 30000, index: 2, id: 10168, cond: 30000, index: 3, id: 10175, cond: 30000
11:34:11.943 DBG | [AutoRetainer] Task IntelligentRepairTask completed successfully
11:34:11.960 DBG | [AutoRetainer] Starting to execute task: SelectDeploy
11:34:31.969 WRN | [AutoRetainer] Clearing 7 remaining tasks because of timeout
11:34:31.969 WRN | [AutoRetainer] Task SelectDeploy took too long to execute
11:34:31.969 WRN |    at ECommons.Automation.TaskManager.Tick(Object _) in C:\VS\AutoRetainer\ECommons\ECommons\Automation\TaskManager.cs:line 284
11:34:31.969 DBG | [AutoRetainer] FPS restrictions restored
11:34:31.969 DBG | [AutoRetainer] Restoring FFXIV process priority.
```
</details>

**Comment by Limiana** [comment]
Hello!
Airships currently support only redeploy option. 
We're willing to enhance airship support but for that we need long-term (few months) access to FC with airships that will be solely dedicated to development and experiments.

**Comment by zbee** [comment]
I see, okay.

Well, it will be a long while before my subs are levelled up enough to unlock my last sub slot, and I removed my airship after realizing this won't level it; so I have an empty airship slot available, and will for a long time.

So that could be used for development along with my over-abundance of company coins, if you're interested in that, or I may fork to try to do that if you're not interested in developing out airship features presently

**Comment by Limiana** [comment]
the main issue is that you can only run total of 4 vessels, be it airships or submarines
so for airship experiments submarines can't be run
you can have both 4 airships and 4 submarines but you can run only 4 of them, if that makes sense

**Comment by zbee** [comment]
Yes, my deployables are not particularly advanced ha.

I did mean for just the 1 airship slot to be used. I could remove the 1 sub I just added, giving 2 airship slots.
I am currently running 3 subs (1 of which is the brand new one that could be dismantled if useful), so there would be space for the 1 or 2 airships to both be running.

So, I could offer 2 airship slots both of which could be run. And if you're saying that I can have 4 airships made while having the 3 subs I currently have, and just only run 4 deployables at once: then I can just not send out my subs.

**Comment by Limiana** [comment]
Airship slots and submersible slots are not dependent on each other. You can have 4 airships and 4 submarines at the same time, you just can't have them running all at the same time (if you're running airships, your submarines will just stay and chill).
You unlock more airship slots in the same way as submarines, by exploring sectors and buying airship permissions with fc credits. 
If you're willing to provide an fc and airship parts to assist with airship development, we will take that. Though, until mid january   you can keep levelling up submarines, as until then I'm going to be busy with other things for sure

**Comment by zbee** [comment]
Alright, perfect; I am definitely willing to do that.

I'll dig into this and try to have as many airship slots available by then -I think currently I only have 2-, amass some supplies for them to run, and will put together a Teamcraft to slowly work through to have stuff parts ready to outfit them with, etc.

**Comment by zbee** [comment]
@Limiana Not sure if you're still into the idea, but if so, I did a whack amount of investigating and crafting and have 2 airship slots and a lot of parts ready.
I wanted to wait until I got 3 or even 4 slots, but I just have not been very active these past couple months.

I have a several hundred repair materials and ceruleum tanks.
Additionally, I have a few million company credits and my retainers gather what is needed for the repair tanks.
I have a level 34 (40 needed to get the third slot) and level 13 airship.
These airships could be scrapped and restarted, or continued as is useful.

I have crafted the following parts:
<table>
<thead>
  <tr>
    <th>Rank</th>
    <th>Hull</th>
    <th>Rigging</th>
    <th>Forecastle</th>
    <th>Aftcastle</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>1</td>
    <td><b>2x</b> Bronco</td>
    <td><b>2x</b> Bronco</td>
    <td><b>2x</b> Bronco</td>
    <td><b>2x</b> Bronco</td>
  </tr>
  <tr>
    <td>5</td>
    <td><b>1x</b> Invincible</td>
    <td><b>1x</b> Invincible</td>
    <td><b>1x</b> Invincible</td>
    <td><b>1x</b> Invincible</td>
  </tr>
  <tr>
    <td>15</td>
    <td><b>1x</b> Enterprise</td>
    <td><b>1x</b> Enterprise</td>
    <td><b>1x</b> Enterprise</td>
    <td><b>1x</b> Enterprise</td>
  </tr>
  <tr>
    <td>25</td>
    <td><b>2x</b> Invincible II</td>
    <td><b>2x</b> Invincible II</td>
    <td><b>2x</b> Invincible II</td>
    <td><b>2x</b> Invincible II</td>
  </tr>
</tbody>
</table>

I don't really remember why I did it this way ... I probably didn't understand parts' component limits yet, but whatever. One set of the Invincible II's could be sold if having other parts would make sense.

And finally, I have an FC member role setup that as full access to the airships and their parts stored in the company chest.

It's not as ready as I would have liked it to be, but hopefully it's enough to be useful.

**Comment by Limiana** [comment]
Hello! Probably I wouldn't be able to implement airship until a bit into Dawntrail as there is quite a large backlog right now

**Comment by zbee** [comment]
Understood, thanks for the update.
I have 3 ships now, likely 4 soon, so it will definitely be ready for whenever the time is available.
