### ISSUE TITLE
Error in 4.3.0.4

### ISSUE THREAD

**Issue by DiST1122** [PunishXIV/AutoRetainer#70]
There was an error with the ability to sell items to a command.

[Debug@2024-06-13 오후 6:24:54 +09:00] Seals: 26321/80000, for item 1937 | 머나먼 학살자 바지: True
[Debug@2024-06-13 오후 6:24:54 +09:00] Handing in item 머나먼 학살자 바지 for 1937 seals (index=0)
[Error@2024-06-13 오후 6:24:54 +09:00] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.InvokeHandin(AtkUnitBase* addon, Int32 which) in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 284
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.HandleGCList() in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 176

This was working fine until the previous version.

**Comment by Limiana** [comment]
Please type `/xlbranch` and confirm that you're using "release" branch

**Comment by DiST1122** [comment]
> Please type `/xlbranch` and confirm that you're using "release" branch

I already used "release" branch.

**Comment by Limiana** [comment]
> > Please type `/xlbranch` and confirm that you're using "release" branch
> 
> I already used "release" branch.

Please attach your whole log `%appdata%\XIVLauncher\dalamud.log` right after experiencing this issue

**Comment by DiST1122** [comment]
This logs found from dalamud.log keyword by "AutoRetainer"

--------------------------------
2024-06-14 10:57:33.145 +09:00 [INF] [PLUGINM] AutoRetainer defaultState: true wantedByAnyProfile: true loadPlugin: true
2024-06-14 10:57:33.145 +09:00 [INF] [LOCALPLUGIN] Loading AutoRetainer.dll
2024-06-14 10:57:35.697 +09:00 [INF] [AutoRetainer] This is ECommons v2.2.0.2 (release build with forms) and AutoRetainer v4.3.0.4. Hello!
2024-06-14 10:57:35.699 +09:00 [INF] [AutoRetainer] Advanced Dalamud reflection module has been requested
2024-06-14 10:57:35.777 +09:00 [INF] [AutoRetainer] FFXIV instances: 1
2024-06-14 10:57:35.778 +09:00 [INF] [LOCALPLUGIN] Finished loading AutoRetainer
2024-06-14 10:57:37.621 +09:00 [INF] [AutoRetainer] Migrating conditions are not met, skipping...
2024-06-14 10:57:38.103 +09:00 [INF] [AutoRetainer] AutoCutsceneSkipper requested
2024-06-14 10:57:38.104 +09:00 [INF] [AutoRetainer] Found cutscene skip condition address at 0x00007FF7A58D56A3
2024-06-14 10:57:38.104 +09:00 [INF] [AutoRetainer] AutoCutsceneSkipper initialized
2024-06-14 10:57:38.108 +09:00 [INF] [AutoRetainer] AutoRetainer v4.3.0.4 is ready.
2024-06-14 10:57:38.306 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_GCContinuation.EnqueueInitiation as IPC method (0)
2024-06-14 10:57:38.306 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.GC.EnqueueInitiation with method AutoRetainer.Modules.EzIPCManagers.IPC_GCContinuation.EnqueueInitiation
2024-06-14 10:57:38.308 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_GCContinuation.GetGCInfo as IPC method (0)
2024-06-14 10:57:38.308 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.GC.GetGCInfo with method AutoRetainer.Modules.EzIPCManagers.IPC_GCContinuation.GetGCInfo
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.IsBusy as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.IsBusy with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.IsBusy
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.GetEnabledRetainers as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.GetEnabledRetainers with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.GetEnabledRetainers
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.AreAnyRetainersAvailableForCurrentChara as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.AreAnyRetainersAvailableForCurrentChara with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.AreAnyRetainersAvailableForCurrentChara
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.AbortAllTasks as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.AbortAllTasks with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.AbortAllTasks
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.DisableAllFunctions as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.DisableAllFunctions with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.DisableAllFunctions
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.EnableMultiMode as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.EnableMultiMode with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.EnableMultiMode
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.GetInventoryFreeSlotCount as IPC method (0)
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.GetInventoryFreeSlotCount with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.GetInventoryFreeSlotCount
2024-06-14 10:57:38.309 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Attempting to register IPC_PluginState.EnqueueHET as IPC method (2)
2024-06-14 10:57:38.310 +09:00 [INF] [AutoRetainer] [EzIPC Provider] Registering IPC method AutoRetainer.PluginState.EnqueueHET with method AutoRetainer.Modules.EzIPCManagers.IPC_PluginState.EnqueueHET
2024-06-14 10:57:38.420 +09:00 [INF] [AutoRetainer] Autologin module initialized
2024-06-14 19:34:48.733 +09:00 [ERR] [AutoRetainer] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.InvokeHandin(AtkUnitBase* addon, Int32 which) in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 284
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.HandleGCList() in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 176

**Comment by jiangwwwei** [comment]
> > > Please type `/xlbranch` and confirm that you're using "release" branch
> > 
> > 
> > I already used "release" branch.
> 
> Please attach your whole log `%appdata%\XIVLauncher\dalamud.log` right after experiencing this issue


[dalamud.log](https://github.com/user-attachments/files/15866475/dalamud.log)

**Comment by DiST1122** [comment]
> > > > Please type `/xlbranch` and confirm that you're using "release" branch
> > > 
> > > 
> > > I already used "release" branch.
> > 
> > 
> > Please attach your whole log `%appdata%\XIVLauncher\dalamud.log` right after experiencing this issue
> 
> [dalamud.log](https://github.com/user-attachments/files/15866475/dalamud.log)


I saw this log after this issuse.


2024-06-17 20:50:13.362 +09:00 [ERR] [AutoRetainer] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.InvokeHandin(AtkUnitBase* addon, Int32 which) in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 284
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.HandleGCList() in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 176

**Comment by Limiana** [comment]
> > > > Please type `/xlbranch` and confirm that you're using "release" branch
> > > 
> > > 
> > > I already used "release" branch.
> > 
> > 
> > Please attach your whole log `%appdata%\XIVLauncher\dalamud.log` right after experiencing this issue
> 
> [dalamud.log](https://github.com/user-attachments/files/15866475/dalamud.log)

Your Dalamud version seems to be not correct. If you have release branch selected in `/xlbranch`, try deleting contents of `%appdata%\XIVLauncher\addon\Hooks` folder and starting the game again

**Comment by BlueSky16st** [comment]
Hello, I have a same problem. I used your method but did'n work
The AutoRetainer plugin version is v4.3.0.5.

> [2024/6/23 13:56:25 +08:00] Seals: 25348/90000, for item 1879 | 星战士游击战铠: True
> [2024/6/23 13:56:25 +08:00] Handing in item 星战士游击战铠 for 1879 seals (index=0)
> [2024/6/23 13:56:25 +08:00] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.InvokeHandin(AtkUnitBase* addon, Int32 which) in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 284
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.HandleGCList() in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 176


![image](https://github.com/PunishXIV/AutoRetainer/assets/22427590/e6c77d5c-6e82-491c-affb-abb0d79af1e1)

**Comment by warknight1211** [comment]
AutoRetainer plugin version is v4.3.0.5
"release" branch
game server is CN
i try delete the plugin and file [Roaming\installedPlugins\AutoRetainer] and file [Roaming\pluginConfigs\AutoRetainer]，then reinstall，but nothing change，the problem is still

[Expert Delivery.txt](https://github.com/user-attachments/files/16006864/Expert.Delivery.txt)
[Entrust Duplicates.txt](https://github.com/user-attachments/files/16006865/Entrust.Duplicates.txt)
[dalamud.log](https://github.com/user-attachments/files/16006867/dalamud.log)

**Comment by Limiana** [comment]
The issue is out of date, and plugin should work on CN nowadays just fine
