### ISSUE TITLE
Exception during [Enable Automatic Expert Delivery] and [Entrust Duplicates]

### ISSUE THREAD

**Issue by jiangwwwei** [PunishXIV/AutoRetainer#72]
This problem only occurs in versions v4.3.0.4 and v4.3.0.5; previous versions did not have this issue.

When I check the [Enable Automatic Expert Delivery] button, it does not work properly, and the checkbox cannot be ticked. The error message in the log is as follows (However, my computer only has a Disk C, and there is no Disk D.):

> [2024/6/16 21:51:09 +08:00] Seals: 17846/90000, for item 1180 | 征服衬裤: True
> [2024/6/16 21:51:09 +08:00] Handing in item 征服衬裤 for 1180 seals (index=0)
> [2024/6/16 21:50:34 +08:00] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.InvokeHandin(AtkUnitBase* addon, Int32 which) in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 284
   at AutoRetainer.Modules.GcHandin.AutoGCHandin.HandleGCList() in D:\VS\AutoRetainer\AutoRetainer\Modules\GcHandin\AutoGCHandin.cs:line 176

---------------------------------------
Additionally, when the retainer enables the [Entrust Duplicates] option, they will halt at the retainer's backpack interface without any actions, and the error message in the log at this time is as follows:

   > [2024/6/16 22:07:39 +08:00] Starting to execute task: <Enqueue>b__2_3
   > [2024/6/16 22:07:39 +08:00] Firing callback: InventoryRetainerLarge, valueCount = 1, updateStatte = False, values:
   > [2024/6/16 22:07:39 +08:00] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at ECommons.Automation.Callback.FireRaw(AtkUnitBase* Base, Int32 valueCount, AtkValue* values, Byte updateState) in D:\VS\AutoRetainer\ECommons\ECommons\Automation\Callback.cs:line 80
   at ECommons.Automation.Callback.Fire(AtkUnitBase* Base, Boolean updateState, Object[] values) in D:\VS\AutoRetainer\ECommons\ECommons\Automation\Callback.cs:line 137
   at AutoRetainer.Scheduler.Handlers.RetainerHandlers.ClickEntrustDuplicates() in D:\VS\AutoRetainer\AutoRetainer\Scheduler\Handlers\RetainerHandlers.cs:line 205
   at AutoRetainer.Scheduler.Tasks.TaskEntrustDuplicates.<>c.<Enqueue>b__2_3() in D:\VS\AutoRetainer\AutoRetainer\Scheduler\Tasks\TaskEntrustDuplicates.cs:line 44
   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in D:\VS\AutoRetainer\ECommons\ECommons\Automation\LegacyTaskManager\TaskManager.cs:line 141

**Comment by Limiana** [comment]
Hello! please make sure that you have "release" selected in `/xlbranch`, if you do, please attach full dalamud.log file

**Comment by Limiana** [comment]
Duplicate issue of https://github.com/PunishXIV/AutoRetainer/issues/70
